name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    strategy:
      fail-fast: false
         # node-version: [12.x]
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: 
        - "3.7"
        - "3.8"
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12-dev"

    runs-on: ubuntu-latest
    
    name: Test 
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4 
      with:
        python-version: ${{ matrix.python-version }} 
    
    - name: Install dependencies
      run: python -m pip install --upgrade pip |
        pip install pytest .  |
        pip install -r requirements.txt

    - name: Run tests
      run: pytest
 
